### ISSUE TITLE
Script not running when uncommited changes in git

### ISSUE THREAD

**Issue by DagobertDokate** [passsy/gradle-GitVersioner#24]
I have use the script now for a month. But now, when i have uncommited changes in mit git repo,  the script is not running successful. Is there a debug view or something else? Gradle's debug says nothing. Just script applyed and running.

Kind regards

**Comment by passsy** [comment]
This script isn't maintained for years. Please use the gradle plugin https://github.com/passsy/gradle-gitVersioner-plugin
